version: '3'

rpc:
  listen: tcp://0.0.0.0:6002

server:
  command: "php worker.php"
  env:
    TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS}
    TEMPORAL_NAMESPACE: ${TEMPORAL_NAMESPACE}

http:
  address: 127.0.0.1:10085
  pool:
    num_workers: 2
    allocate_timeout: 60s
    destroy_timeout: 1s
    dynamic_allocator:
      max_workers: 25
      spawn_rate: 10
      idle_timeout: 10s
# Add Temporal configuration
temporal:
  address: ${TEMPORAL_ADDRESS}
  activities:
    num_workers: 2
  command: "php worker.php"  
  codec: proto

logs:
  mode: development
  level: debug
  encoding: console
  output: stdout
  err_output: stderr

status:
  address: 0.0.0.0:2114

# Добавляем конфигурацию для воркеров
workers:
  command: "php worker.php"
  pool:
    num_workers: 1
    allocate_timeout: 60s
    destroy_timeout: 60s
