version: "3.8"
services:
  cassandra:
    image: cassandra:4.1.3
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=temporal
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 15s
      timeout: 5s
      retries: 30
    networks:
      - temporal-network
    volumes:
      - cassandra_data:/var/lib/cassandra

  temporal:
    image: temporalio/auto-setup:1.22.4
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - CASSANDRA_SEEDS=cassandra
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development.yaml
      - ENABLE_ES=false
      - CASSANDRA_PORT=9042
      - CASSANDRA_DC=datacenter1
    volumes:
      - ./config/dynamicconfig:/etc/temporal/config/dynamicconfig
    ports:
      - "7233:7233"
    networks:
      - temporal-network
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "cluster", "health"]
      interval: 15s
      timeout: 5s
      retries: 30

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.4
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - temporal-network

  temporal-ui:
    image: temporalio/ui:2.21.3
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8082
    ports:
      - "8082:8080"
    depends_on:
      - temporal
    networks:
      - temporal-network

  roadrunner:
    build: .
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
    networks:
      - temporal-network
    depends_on:
      temporal:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./worker.php:/app/worker.php
      - ./start_wf.php:/app/start_wf.php
      - ./.rr.yaml:/app/.rr.yaml
    command: [ "rr", "serve", "-c", ".rr.yaml" ]

  file-server:
    build: ./file-server
    ports:
      - "5001:5000"
    volumes:
      - ./file-server/data:/app/data
    networks:
      - temporal-network

networks:
  temporal-network:
    driver: bridge

volumes:
  cassandra_data:
